[IV-24-25] Entrega Objetivo 2
FabriConde/CLIMB-VR pull request #11
Opened 2024-10-25 09:58 UTC by giorgiogiovanni

__Sobre la estructura del repositorio__
* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?
Sobre el planteamiento
* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?
Sobre el análisis del problema
* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

__Sobre el código__

* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-10-25 11:40 UTC, giorgiogiovanni commented
@FabriConde Espero que añadas el milestone y me hagas una revisión

2024-10-29 11:56 UTC, giorgiogiovanni commented
@FabriConde listo para revisar :construction_worker:

2024-10-29 21:04 UTC, FabriConde commented
> @FabriConde listo para revisar 👷

Lo único que veo mal es lo que te comenté en la revisión

2024-10-31 11:20 UTC, giorgiogiovanni commented
@FabriConde perdona mi ignorancia, pero no veo ninguna revisión. No se si no consolidates comentarios... las verdad.

2024-11-08 12:09 UTC, FabriConde commented
@giorgiogiovanni Perdona que tenía la revisión como pendiente y por eso no te salía

2024-11-08 12:27 UTC, giorgiogiovanni commented on internal/via.go
> +type Via struct {
Repasando la historia de usuario es verdad que se expresa como informacion opcional como por ejemplo... Aunque consideré que era relevante y lo externalicé a una variable propia. 
Resuelto entonces y reducido solo a `infoExtra`

Quedo a la espera de algun comentario más o solicitamos revisión 🔝

2024-11-08 12:28 UTC, giorgiogiovanni commented
@FabriConde 
Repasando la historia de usuario es verdad que se expresa como informacion opcional como por ejemplo... Aunque consideré que era relevante y lo externalicé a una variable propia. Resuelto entonces y reducido solo a `infoExtra`

Quedo a la espera de algun comentario más o solicitamos revisión 🔝

2024-11-08 14:56 UTC, FabriConde approved these changes

2024-11-08 14:58 UTC, giorgiogiovanni commented
Listo para revisión @JJ

2024-11-08 18:37 UTC, JJ requested changes
Entender el YAML también es importante...

2024-11-11 09:19 UTC, giorgiogiovanni commented on iv.yaml
> +entidad: internal/sector.go
Tiene razon. El problema a veces de ir con el piloto automatico con cosas que no solemos usar. un error claramente.

2024-11-11 09:19 UTC, giorgiogiovanni commented
YAML arreglado @JJ

2024-11-11 10:29 UTC, JJ approved these changes
:+1:

2024-11-11 10:29 UTC, JJ commented on internal/via.go
> +	9cPlus	= 10
Todo esto me parece un poco excesivo para un PMV o para un modelo, pero si a @FabriConde no tengo mucho que añadir.

2024-11-11 15:21 UTC, merged