[IV-24-25] Objetivo 4
FabriConde/CLIMB-VR pull request #18
Opened 2024-11-25 23:11 UTC by FabriConde

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [x] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [x] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [x] ¿Se han testeado también las excepciones?
#15 #17 #19 #20 #21 #22 # 23 #24 #25 #26 #27 #28 #29 #30 #31 #32 #22 #34 #35 #36 #37 #38 #39 #40 #41 #42 #43 #53 #54 #55 #56

2024-11-26 20:47 UTC, hossam1522 reviewed
Buenas, soy uno de los encargados de revisar tu issue. Lo que es la implementación en sí la veo correcta, pero veo un problema con las issues. Considero que hay muy pocas issues para la gran cantidad de código que has añadido. Por ejemplo, ¿por qué no crear una issue para los tests creados en vez de considerarlos dentro de la issue de la elección de herramienta?

De todas formas los commits ya están hechos, te lo comento para próximas veces.

Lo que sí te voy a pedir que le des una vuelta es lo siguiente:

> - [x] ¿Hay un camino claro que permita ir desde el código hasta la historia de
usuario que desarrolla, pasando por el mensaje de commit y el issue
correspondiente?

Has marcado esto, pero realmente el camino no está claro. Sí, puedo ir desde el commit hasta la issue correspondiente pero:
1 - Las issues no están asociadas a ninguna historia de usuario. ¿Qué lógica de negocio te refieres, referida a cuál problema?
2 - No tiene mucho que ver con este punto, pero las issues no explican ningún problema. Por ejemplo, ¿para qué quieres elegir una herramienta de test? ¿No convendría explicarlo en la issue?

> [x] ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
se ha documentado cómo se ha hecho?

¿Dónde se ha documentado?



Por lo demás, todo correcto. ¡Mucho ánimo!

2024-11-27 10:41 UTC, FabriConde commented
Buenas @hossam1522, gracias por tú correción.
> Buenas, soy uno de los encargados de revisar tu issue. Lo que es la implementación en sí la veo correcta, pero veo un problema con las issues. Considero que hay muy pocas issues para la gran cantidad de código que has añadido. Por ejemplo, ¿por qué no crear una issue para los tests creados en vez de considerarlos dentro de la issue de la elección de herramienta?
> 
> De todas formas los commits ya están hechos, te lo comento para próximas veces.

El hecho de crear pocas issues es proque en otros objetivos creé issues de más y está vez no quise hacerlo.
> 1 - Las issues no están asociadas a ninguna historia de usuario. ¿Qué lógica de negocio te refieres, referida a cuál problema?

Solo he añadido el M1, pero es verdad que no he explicado bien la issue. Lo actualizo

> 2 - No tiene mucho que ver con este punto, pero las issues no explican ningún problema. Por ejemplo, ¿para qué quieres elegir una herramienta de test? ¿No convendría explicarlo en la issue?

Tienes razón, he creado un documento donde lo explico, pero en la issue no lo he hecho.

2024-11-27 12:58 UTC, FabriConde commented
@hossam1522 
- Se han actualizado las issues para que tengan más información. 
- Se añaden los principios F.I.R.S.T: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/a5835319b33a0b2a869ee37c6a29a7716707d4d0
- Se corrige la conclusión de los principios F.I.R.S.T: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/3e622c902f7374f90efa9c157d5364b68a40eab9

2024-11-27 13:53 UTC, hossam1522 approved these changes
Una vez arreglado lo comentado, por mi parte está correcto.

2024-11-28 07:44 UTC, JJ reviewed
1. Sigue las mejores prácticas en estructura de retorno de funciones en Go
2. Sigue las mejores prácticas en setup de directorios.
También revisa los errores comunes en este antes de pedir una nueva revisión. Y gracias a @hossam1522 por su revisión.

2024-11-28 08:55 UTC, FabriConde commented
> 1. Sigue las mejores prácticas en estructura de retorno de funciones en Go

Corregido es este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/130302a96ec3352ebff2e609375f5b843a0f5134
> 2. Sigue las mejores prácticas en setup de directorios.

Corregido es estos commits:
- https://github.com/FabriConde/CLIMB-VR/pull/18/commits/dc4b276537c309a0f156da8b4a4ebde58a340d72
- https://github.com/FabriConde/CLIMB-VR/pull/18/commits/b2eb6750f8369c64210b1c0562bc705f57c87588
- https://github.com/FabriConde/CLIMB-VR/pull/18/commits/83be80c776c33e731d7dfbbe5fb28966890aa3a2
- https://github.com/FabriConde/CLIMB-VR/pull/18/commits/a9da841b6caf2a86cead191f149ba914036d739b

2024-11-28 09:05 UTC, JJ reviewed
Por favor, los errores comunes son importantes. Miradlos y os ayudarán.

2024-11-28 09:05 UTC, JJ commented on docs/herramientas-test.md
> +# [Herramientas de test](https://github.com/FabriConde/CLIMB-VR/issues/15)
Por favor, mira los errores comunes.

2025-01-10 20:38 UTC, FabriConde commented
@JJ Listo para revisar.

Te comento lo que he hecho
- He decidido que el texto va a estar en un fichero de texto llamado texto_sector.txt. 
- He actualizado el la HU001 #2 y el [M1](https://github.com/FabriConde/CLIMB-VR/milestone/3).
- Se añade el formato que va a tener el texto: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/e9e1aafdad07f15ad9d4cb9890deae9520ff2d8d
- Ahora al tener que leer desde un fichero he tenido que eliminar todo el código innesario, que los he hecho en estos commits:
  - Se eliman Testify del proyecto: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/e9f1c514dc95e850edd131a844a337f5098a6ad7
  - Se elimina todo el código innecesario:  
    - Como ahora tiene un formato concreto se elimina todo el código: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/c78c4281d21d43f3f6162495c1607bcb7778621a
    - Se elimina el mapa de sectores ya que solo se va a poder añadir un solo sector: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/afd6a4c12683d1852c48ee4696f555d38f1a0b50
    - Se elimina funciones de sector que no se usan: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/4c383bc3276f9d4a2b31253519005a48e8729150
    - Se eliminan los test anteriores: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/4d5ca0a59c29669a62622ac195f7c21c3512f8cb
- Se crea un archivo donde se va a leer el contenido que tiene el fichero de texto: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/61074c7dcae43165b2c6789202ba662356382755 https://github.com/FabriConde/CLIMB-VR/pull/18/commits/1755f31433e28fe01f708cfcaa36d8338c0ccd66
- Se crea un funcion que es capaz de interpretar el fichero: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/e39087b5d7482223805430ad369d9eff76ff3e41
- Se crean las funciones necesarias para añadir una via: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/3f59c753ed6c2d85fbd88d6947a6f7bb736f0aa6
- Se termina la función para que se pueda crear el sector: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/4c61a61fca6d66ac521381bb96f0123fc5a3e9d3
- Se crean los test para poder verificar que se puede leer el fichero: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/e39cd5fabcdde0f4b4a1bbcd77a76aecdc37b653
-  Se crean los test para poder verificar que se pueden crear las vías: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/667056f12f35881624ae01e0f7bfd83f8f7d8fa8
-  Se crean los test para poder verificar que se puede crear el sector: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/3dd4a0b20ad611aa4f63d7505f1e09665a1faaa1
- Se crean las issues correspoendientes para cada problema

Se que han sido muchas cambios, pero es que con estos cambios he eliminado mucho código innecesario, ya sea de la lógica como de los test.

2025-01-13 13:17 UTC, JJ requested changes
Sin haber hecho correctamente la elección, es difícil que el código se haya llevado a cabo correctamente, por eso en esta vuelta no voy a entrar en él. En todo caso, te agradecería que miraras los [errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md) por si hubieras caído en alguno de ellos.

2025-01-13 13:17 UTC, JJ commented on docs/aserciones.md
> +Después de evaluar las bibliotecas, he decidido utilizar el paquete estándar de Go `testing` para mis pruebas. Las aserciones en el paquete `testing` son simples y directas, lo que es ideal para este
¿Eliges una que no has considerado arriba? ¿Y que por tanto no sabemos si sigue los criterios o no? ¿Ni siquiera si es o no una biblioteca de aserciones?

2025-01-13 13:17 UTC, JJ commented on docs/test_runners.md
> +## go test (Test Runner Estándar)
En [el guión](https://jj.github.io/IV/documentos/proyecto/4.Tests) se distingue entre *test runners* o *frameworks* y *herramientas CLI para ejecutar los tests*. ¿Cuál de las dos cosas estás poniendo aquí?

2025-01-13 20:08 UTC, FabriConde commented on docs/aserciones.md
> +Después de evaluar las bibliotecas, he decidido utilizar el paquete estándar de Go `testing` para mis pruebas. Las aserciones en el paquete `testing` son simples y directas, lo que es ideal para este
Tienes razón, se corrige en los siguentes commits:
- Se ha elimina este fichero para que quede más claro la elección de las herramientas: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/42280667dafa4985bbe8a16e4965b3ad631bf901
- Se añade un nuevo fichero en el que se describe lo que hace y lo que es el paquete testing, así se tiene en cuenta a la hora de tomar la decisión: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/c73e0fd9bc5066b08cd71b3b8ebbb4e3a8a4898a

2025-01-13 20:08 UTC, FabriConde commented on docs/test_runners.md
> +## go test (Test Runner Estándar)
Me he equivocado, me estaba refiriendo al test runner y `go test` no es el test runner, se corrige en los siguentes commits:
- Se ha elimina este fichero para que quede más claro la elección de las herramientas: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/4b0827c653e22b738fb95f224497313056037fee
- Se añade un nuevo fichero en el que se corrige la confusión y se añade la elección del comando CLI para ejecutar los test: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/c73e0fd9bc5066b08cd71b3b8ebbb4e3a8a4898a

2025-01-13 20:09 UTC, FabriConde commented
@JJ Lista para revisar

2025-01-15 06:47 UTC, JJ requested changes
Aparte de todo lo comentado, parece que solamente tienes un fichero de prueba.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +Go cuenta con un sistema de pruebas integrado directamente en el lenguaje. Se usa el paquete `testing` y el comando `go test`, que automatiza la ejecución de cualquier función de la forma `func TestX
Tampoco pasa nada si le pones un título al documento.
Por otro lado, podrías comentar que ese paquete usa la convención de Go para devolver errores en las funciones y considerarlo como aserciones fallidas.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +**[El paquete testing](https://pkg.go.dev/testing) y el comando `go test`**:
Entre otras cosas, si no pones el título no sé de qué estás hablando. Y si no sé de qué estás hablando, no puedo evaluar si es correcto o no.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +- Permite ejecutar benchmarks.
¿Te parece que esto sea relevante para evaluar tu objetivo?

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +- Las aserciones tienen que ser simples ya que para este proyecto no hace falta que sean de tipo BDD.
1. Que no sean BDD es totalmente arbitrario.
2. Las aserciones de ese tipo no son más complicadas. Simplemente usan más palabras y se acercan más al lenguaje natural.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +## Test Runners
¿Es un gran problema que pongas *a continuación* la decisión?

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +- Debe permitir la creación y ejecución de subtests, facilitando la organización jerárquica de pruebas.
Esa es la definición de un test runner.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +## CLI para ejecutar tests
¿También es un gran problema poner la decisión?

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +En algunos lenguajes o marcos de programación, como Go o Deno, ya se incluye una suborden `test` que facilita la ejecución de las pruebas. En el caso de Go, el comando estándar para ejecutar pruebas
Ya lo has dicho arriba. ¿Repetir aquí lo que pone en otro sitio es relevante?

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +- [Ginkgo](https://github.com/onsi/ginkgo): Un marco de pruebas BDD que se integra con `go test` y ofrece una salida más estructurada.
No solo ofrece una salida más estructurada.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +Para las aserciones y para el test runner he decidido usar el paquete `testing` porque las aserciones en el paquete `testing` son simples y directas, lo que es ideal para este proyecto que no requier
O sea, que otra vez has decidido usar algo que no has puesto, no usar aserciones sino directamente los errores de Go. Estas ni son simples (son errores) ni se puede decir que tengan (o no) deuda técnica. No solamente cometes un error, sino que [no solucionas lo que se te comentó](https://github.com/FabriConde/CLIMB-VR/pull/18#discussion_r1913174688).
Llegado a este punto podría dejar fácilmente de corregir, cuando más llevamos ya 111 comentarios. Pero vamos a revisar el código.

2025-01-15 06:47 UTC, JJ commented on docs/testing.md
> +- Las aserciones tienen que ser simples ya que para este proyecto no hace falta que sean de tipo BDD.
Aquí sigues sin solucionar [este comentario](https://github.com/FabriConde/CLIMB-VR/pull/18#discussion_r1899470569), continuando con los cambios de palabras y además siguiendo con un criterio que por lo demás no usas. Ya te lo dije hace dos semanas, hace unos 15 o 20 comentarios. Si te parece que incurrir en los mismos errores y yo volver a decirte que son errores es una forma eficiente de emplear el tiempo de los dos, continúa por ese camino. Si opinas otra cosa, por favor, haz caso ya a lo que se te dice.

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +	return crearSectorDesdeTexto(contenido)
¿Te parece que una función que se llame `LeerFichero` en realidad llame a otra que crea un sector desde texto  sigue, para empezar, el principio de la responsabilidad única y, para seguir, tiene una denominación correcta?

¿Te parece, por otro lado, que llamar a una función en Go sin tener en cuenta la convención de que puede devolver un error es correcto?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +		return "", fmt.Errorf("error al leer el archivo: %v", err)
¿Devolver una cadena vacía en vez de nil es la convención correcta en Go?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +	lineas := strings.Split(texto, "\r\n")
¿Te parece que trabajar con la información *de todo el sector* y *de cada una de las líneas* corresponde al principio de responsabilidad única? Si quieres testearlo, ¿cuantas opciones diferentes tendrás que hacer?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +func crearSectorDesdeTexto(texto string) (*Sector, error) {
Si al final llamas al constructor, ¿igual no sería razonable que esto *fuera* el constructor?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +	return NewSector(nombreSector, descripcionSector, viasDelSector), nil
¿Te parece una buena práctica llamar a un constructor sin comprobar si ha devuelto un objeto válido?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +		if len(partes) < 3 {
¿usar números mágicos corresponde a las mejores prácticas en programación? Me han comentado en clase que hasta os lo dicen en MP

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero.go
> +		return 0, err
Estás devolviendo todo tipo de valores junto con el err. ¿Eso corresponde a las mejores prácticas en Go?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero_test.go
> +	if err != nil {
¿Estás solo comprobando que no da error, cuando esta función devuelve un objeto complejo? Si estás haciéndolo más abajo, y necesitas dos tests para una sola función, una vez más prueba de que estás incumpliendo el SRP

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero_test.go
> +	ruta := filepath.Join("testdata", "archivo_vacio.txt")
¿Esto lo pide la historia de usuario y por tanto debe estar en un producto mínimamente viable?
¿Te das cuenta que añadir 20 tests sin nada que ver con la lógica de negocio solo aumenta el trabajo de la persona que tiene que revisar?

2025-01-15 06:47 UTC, JJ commented on internal/models/leer_fichero_test.go
> +func TestCrearViasDelSectorConDificultadInvalida(t *testing.T) {
DRY: no repitas el mismo código con diferentes datos. Incluso aunque tengas diferentes entradas y salidas, lo correcto es repetir los datos, no el código. Una vez más, más código es más código a revisar.

2025-01-15 22:04 UTC, FabriConde commented on internal/models/leer_fichero_test.go
> +	ruta := filepath.Join("testdata", "archivo_vacio.txt")
Si, lo he añadido en la historia de usuario.

2025-01-15 22:05 UTC, FabriConde commented on internal/models/leer_fichero_test.go
> +func TestCrearViasDelSectorConDificultadInvalida(t *testing.T) {
Se corrige en estos commits: 
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/5e9f858d44b255451de4861bf847e405f223d70e
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/a5d7cd8283954d53db5ef10ce43bf821556b807a
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/caf22e18442a72b692c69dc0b54aaac1ab251dd5

2025-01-15 22:05 UTC, FabriConde commented on internal/models/leer_fichero_test.go
> +	if err != nil {
Se corrige en estos commits: 
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/5e9f858d44b255451de4861bf847e405f223d70e
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/a5d7cd8283954d53db5ef10ce43bf821556b807a
https://github.com/FabriConde/CLIMB-VR/pull/18/commits/caf22e18442a72b692c69dc0b54aaac1ab251dd5

2025-01-15 22:06 UTC, FabriConde commented on internal/models/leer_fichero.go
> +		if len(partes) < 3 {
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/69d0d34bfa3f3846644070f05376e500af53e8aa

2025-01-15 22:06 UTC, FabriConde commented on internal/models/leer_fichero.go
> +	return NewSector(nombreSector, descripcionSector, viasDelSector), nil
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/69d0d34bfa3f3846644070f05376e500af53e8aa

2025-01-15 22:06 UTC, FabriConde commented on internal/models/leer_fichero.go
> +	lineas := strings.Split(texto, "\r\n")
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/69d0d34bfa3f3846644070f05376e500af53e8aa

2025-01-15 22:06 UTC, FabriConde commented on internal/models/leer_fichero.go
> +func crearSectorDesdeTexto(texto string) (*Sector, error) {
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/69d0d34bfa3f3846644070f05376e500af53e8aa

2025-01-15 22:07 UTC, FabriConde commented on internal/models/leer_fichero.go
> +	return crearSectorDesdeTexto(contenido)
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/953358a18a9a80670e4962612fdbe5002e443bdb

2025-01-17 13:31 UTC, JJ requested changes
Por favor, revisa el concepto de historia de usuario y para qué sirven en el desarrollo ágil.

2025-01-17 13:31 UTC, JJ commented on internal/models/leer_fichero.go
> +	contenido, err := LeerFichero(ruta)
Literalmente hace dos cosas: leer el fichero y luego crear el sector.
El principio de responsabilidad única no es algo que se pueda camuflar. Implica que tienes que tener un flujo de trabajo que *no llame a una función desde otra*, sino que vaya integrando todas las transformaciones únicas en un solo programa. Eso lo hace más fácil de depurar y por supuesto de testear.

2025-01-17 13:31 UTC, JJ commented on internal/models/leer_fichero.go
> +func LeerFichero(ruta string) (string, error) {
¿Para qué tienes esto si ya tienes `leerContenidoFichero`? ¿Qué le aporta? ¿A esa función o al cliente?

2025-01-17 13:31 UTC, JJ commented on internal/models/sector.go
> +import (
Ya voy por el 3º commit en el que no sigues la convención **que se os ha pedido desde el objetivo 2**

```
50 caracteres (issue en los primeros)
(espacio en blanco)
líneas de 80 caracteres
```

Eso implica trabajo adicional por parte de la persona que revisa, que tiene que ir pinchando para ver el "titular" del mensaje de commit y por qué se hace.

Aparte de que el hecho de que los commits sean *atómicos* debería indicarte que hicieras este cambio junto con 953358a18a9a80670e4962612fdbe5002e443bdb, porque si no no se entiende por qué has cambiado de sitio `strconv` y `strings`

2025-01-17 13:31 UTC, JJ commented on internal/models/sector.go
> +const infoBasicaParaUnSector = 2
Esta es la 2º cosa que dices en el commit, "eliminar números mágicos". Si no haces commits atómicos, estás obligando a la persona que revisa a que vea cada uno de los cambios si se han hecho o no y como. Por otro lado, los mensajes de commits dicen *por qué* no lo que se hace.
Y deben estar siempre *relacionados* con el issue con el que se ponen. Este tiene el #39, **que no tiene absolutamente nada que ver con la implementación de buenas prácticas*
Finalmente, las constantes en Go deben seguir una convención determinada en los identificadores, igual que cualquier otra estructura de datos. ¿Cuál es la que siguen?

2025-01-17 13:31 UTC, JJ commented on internal/models/leer_fichero_test.go
> +	ruta := filepath.Join("testdata", "archivo_vacio.txt")
Agh. ¿Esa es la buena práctica? ¿si se mete algo que el cliente no pide, se dice al cliente que lo pida? ¿Entendemos lo que significa una historia de usuario?

Esto es lo último que voy a corregir en esta ronda, ya que veo que conceptos que deberían estar claros desde el objetivo 1 en realidad no se tienen tan claros.

2025-01-20 01:08 UTC, FabriConde reviewed
Si, los commit los hice muy mal, intente meterlo todo junto para evitar tener que hacer más commits. No volverá a pasar.
@JJ Revisión

2025-01-20 01:08 UTC, FabriConde commented on internal/models/leer_fichero_test.go
> +	ruta := filepath.Join("testdata", "archivo_vacio.txt")
Se añade el test que comprueba que se puede crear el sector: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/c893b3199d0ceb4ce1a83a30e03cbe33e434c1a1
Se añaden los test que comprueban que se puden crear las vias: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/3b4cfa4323971da35c8032c03b549174af5555df

2025-01-20 01:08 UTC, FabriConde commented on internal/models/leer_fichero_test.go
> +	ruta := filepath.Join("testdata", "archivo_vacio.txt")
> Agh. ¿Esa es la buena práctica? ¿si se mete algo que el cliente no pide, se dice al cliente que lo pida? ¿Entendemos lo que significa una historia de usuario? 

El test TestLeerFicheroArchivoVacio lo hice para aumentar la cobertura de los test, para que se acercara al 100%.

2025-01-20 13:20 UTC, JJ commented on internal/models/sector.go
> +const infoBasicaParaUnSector = 2
Por favor, infórmate de qué convención siguen las constantes. Una convención no solo incluye el Case.

2025-01-20 13:23 UTC, JJ commented
Si has cambiado la línea, ¿no te parece que es suficiente con la información del commit? ¿Tienes que decir además en qué commit lo cambias, a veces mal porque pones otro commit?
Por otro lado, ¿te parece que la cobertura sea algo que se incluye en el PMV? ¿Primero modificas la HU, luego pones algo que no tiene nada que ver con el PMV? (Espero que tu reacción no sea modificar el PMV)

2025-01-20 13:33 UTC, JJ requested changes
Has mejorado algo, pero podrías considerar correctamente las convenciones así como eliminar pruebas innecesarias.

2025-01-20 13:33 UTC, JJ commented on internal/models/sector.go
> +	infoSector := strings.Split(linea, ",")
Sigues usando "cadenas mágicas".
¿Te imaginas que alguien cambie la forma como se escriben los ficheros y tienes que navegar entre 20 módulos para ver dónde está? ¿En vez de simplemente buscar el nombre de la constante?

2025-01-20 13:33 UTC, JJ commented on internal/models/sector.go
> +const infoBasicaParaUnaVia = 3
¿`info` es 3? ¿También sigue la convención de constantes?

2025-01-20 13:33 UTC, JJ commented on internal/models/sector.go
> +const longitudMinima = 3
Longitud mínima, ¿de qué?

2025-01-20 13:33 UTC, JJ commented on internal/models/sector_test.go
> +		t.Errorf("Se esperaba el nombre 'Sector1', pero se obtuvo '%s'", sector.nombre)
¿Ves qué pasa si no usas nombre de constantes? Que el mensaje de error es incorrecto.

2025-01-20 13:33 UTC, JJ commented on internal/models/sector_test.go
> +func testValidarLongitud(t *testing.T, longitud float32, shouldFail bool) {
¿La HU pide que testees esto?
¿De veras crees que es necesario un fichero con 100 líneas, todas las cuales hay que revisar, para satisfacer al cliente en un producto mínimamente viable?

2025-01-20 13:33 UTC, JJ commented on internal/models/sector_test.go
> +func TestValidarLongitud(t *testing.T) {
Esta función se llama igual que la de abajo. ¿Crees que es una buena elección para una, para la otra, o para las dos?

2025-01-20 13:33 UTC, JJ commented on internal/models/sector_test.go
> +	testValidarLongitud(t, 500, true)
¿Te parece que este código, el de la siguiente y el de la anterior, se podrían DRYear usando un array de datos?

2025-01-20 13:33 UTC, JJ commented on internal/models/testdata/texto_sector.txt
> +Sector Avispa,Desde que dejas el coche en el parking seguir el sendero a la derecha
¿Un solo ejemplo es suficiente para validarlo? ¿No hay casuística especial o casis límite para validar que se está cumpliendo lo que pide el cliente?

2025-01-20 16:04 UTC, FabriConde commented on internal/models/sector_test.go
> +func testValidarLongitud(t *testing.T, longitud float32, shouldFail bool) {
Tienes razon, hice los test para intentar que la cobertura fuera la mayor posible, pero eso no es PMV.
Se corrige en este commit:  https://github.com/FabriConde/CLIMB-VR/pull/18/commits/76a6118f427eedd5dc67d70bbd1b636283c38e8d

2025-01-20 16:04 UTC, FabriConde commented on internal/models/sector_test.go
> +	testValidarLongitud(t, 500, true)
Se elimina estos test: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/76a6118f427eedd5dc67d70bbd1b636283c38e8d

2025-01-20 16:04 UTC, FabriConde commented on internal/models/sector_test.go
> +func TestValidarLongitud(t *testing.T) {
Se elimina estos test: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/76a6118f427eedd5dc67d70bbd1b636283c38e8d

2025-01-20 16:08 UTC, FabriConde commented on internal/models/sector_test.go
> +		t.Errorf("Se esperaba el nombre 'Sector1', pero se obtuvo '%s'", sector.nombre)
Se corrige en este commit: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/7fa95aee3b0eeaa3aada5748718028079f4b6422

2025-01-20 16:09 UTC, FabriConde commented on internal/models/testdata/texto_sector.txt
> +Sector Avispa,Desde que dejas el coche en el parking seguir el sendero a la derecha
Con un solo ejemplo del sector es más que suficiente, ya que lo que realmente importa son las vías.

2025-01-21 17:43 UTC, FabriConde commented
@JJ He tenido que hacer unos cambios para que el Objetivo 5 funcione:
Se cambia la forma de leer el fichero: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/08e966702ba7c7b988677ab1b72c7bb9eb90a305
Se crea una nueva función que elimina elemtos vacios de la linea: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/b2cb3d0546a75a950f1ea262a84410c51cc200fb
Se añaden comprobaciones al test de crear el sector para corroborar que el sector se crea correctamente: https://github.com/FabriConde/CLIMB-VR/pull/18/commits/a3334c14e75409a6e92081bdc7a72c569521c6c8

2025-01-21 19:16 UTC, JJ commented
Si tienes que cambiar el código para que funcione el contenedor estás cometiendo un error en una cosa, en otra, o más probablemente en los dos. Si lo que estás haciendo está relacionado con los diferentes formatos de retorno de línea en Mac y en Linux, estás cambiando uno para que no funcione otro y por tanto lo estás haciendo mal. El código tiene que funcionar tanto en local como en cualquier otro entorno de prueba, y además *de la misma forma*.
Y para solucionar también este tipo de problemas tienes 1º que abrir un issue y 2º cerrarlo *cuando tengas un tests que pase*

2025-01-21 19:45 UTC, FabriConde commented
@JJ
> Si tienes que cambiar el código para que funcione el contenedor estás cometiendo un error en una cosa, en otra, o más probablemente en los dos. Si lo que estás haciendo está relacionado con los diferentes formatos de retorno de línea en Mac y en Linux, estás cambiando uno para que no funcione otro y por tanto lo estás haciendo mal. El código tiene que funcionar tanto en local como en cualquier otro entorno de prueba, y además de la misma forma.

De la forma anterior,  al leer el fichero este se dividía con "/r/n" (se hacía por defecto), por ese motivo me daba el test error, porque solo podía leer la primera linea, que es la información del Sector. Ahora lo que hace es que el texto se divide con un "/n"(también por defecto) . Ahora funciona en local y en cualquier entorno de pruebas.

> Y para solucionar también este tipo de problemas tienes 1º que abrir un issue

He añadido los cambios a los issues que tenía para este objetivo porque como todavía sigo modificando el código pensaba que no era necesario. 

> 2º cerrarlo cuando tengas un tests que pase

¿Te refieres a que el Objetivo 5 pase los test? ¿o que al ejecutar los test del objetivo 4 en mi local funcione?

2025-01-22 06:29 UTC, JJ commented
> @JJ
> 
> > Si tienes que cambiar el código para que funcione el contenedor estás cometiendo un error en una cosa, en otra, o más probablemente en los dos. Si lo que estás haciendo está relacionado con los diferentes formatos de retorno de línea en Mac y en Linux, estás cambiando uno para que no funcione otro y por tanto lo estás haciendo mal. El código tiene que funcionar tanto en local como en cualquier otro entorno de prueba, y además de la misma forma.
> 
> De la forma anterior, al leer el fichero este se dividía con "/r/n" (se hacía por defecto), por ese motivo me daba el test error, porque solo podía leer la primera linea, que es la información del Sector. Ahora lo que hace es que el texto se divide con un "/n"(también por defecto) . Ahora funciona en local y en cualquier entorno de pruebas.
> 
> > Y para solucionar también este tipo de problemas tienes 1º que abrir un issue
> 
> He añadido los cambios a los issues que tenía para este objetivo porque como todavía sigo modificando el código pensaba que no era necesario.
> 
> > 2º cerrarlo cuando tengas un tests que pase
> 
> ¿Te refieres a que el Objetivo 5 pase los test? ¿o que al ejecutar los test del objetivo 4 en mi local funcione?

No, me refiero a una regla básica en desarrollo. Cuando hay un problema se crea un issue que lo explique y un test que lo reproduzca. Se cierra el issue cuando el test pasa.

2025-01-22 12:10 UTC, FabriConde commented
@JJ Listo para revisar.

2025-01-22 16:25 UTC, JJ requested changes
No entiendo que a estas alturas introduzcáis errores nuevos en el PR. Vosotros veréis. En todo caso, repasa también los errores comunes antes de solicitar de nuevo revisión.

2025-01-22 16:25 UTC, JJ commented on Makefile
> +	gofmt -e $(CHECK_FILES)
De veras que os agradecería que cambios que no tienen nada que ver con el objetivo los hiciérais antes o después. Y más si son prácticamente cosméticos como aquí.

2025-01-22 16:25 UTC, JJ commented on README.md
> +- `make run`: Ejecutar la aplicación
??? ¿Por qué hace falta ejecutar y qué aplicación? Si además no existe ese objetivo.

2025-01-22 16:57 UTC, FabriConde reviewed
@JJ Listo para revisar.

2025-01-22 16:57 UTC, FabriConde commented on Makefile
> +	gofmt -e $(CHECK_FILES)
Vale, quería que se quedara igual que el siguente objetivo. Además de que las rutas estaban mal y que eliminé ubicacion.go del modelo.

2025-01-24 13:38 UTC, JJ requested changes
Hay una regla muy simple para saber si estás usando bien los issues: ¿te están ayudando a resolver el problema y programar de forma más eficiente y clara? ¿O son una molestia que hay que hacer "porque me lo ha dicho el profe"?
Si sucede lo segundo, lo estás haciendo mal, y lo que es peor, de forma poco eficiente para tu tiempo y para el de lo demás.

2025-01-24 23:15 UTC, FabriConde reviewed
@JJ Listo para revisar

2025-01-24 23:15 UTC, FabriConde commented on internal/models/sector.go
> +import (
No se pueden resolver este comentario ya que está apuntando a los imports. He añadido cambios para especificar porque se usan esos imports, pero sigue apareciendo este comentario.

2025-01-25 08:44 UTC, JJ commented
No hay excepciones con la resolución de comentarios. Tienes que resolverlos todos con un cambio en la línea.
Por otro lado, te animo a que vuelvas a consultar los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md) por si hubieras incurrido en alguno.

2025-01-25 09:03 UTC, JJ commented
> @JJ ¿Para que voy a quitar `import (` del código? No lo entiendo

¿la única forma de cambiarlo es quitar eso? ¿Habrá alguna otra forma de cambiarlo que se te ocurra?

2025-01-25 09:10 UTC, JJ reviewed
Como pone en [el fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-4.md):

> El objetivo de una metodología basada en issues que describen problemas es tanto ayudar a sistematizar la solución a las necesidades del usuario, como poder por la parte del usuario crear código y por la parte del revisor comprobar que el código es correcto. Si un issue no ayuda a crear código, sino que es una obligación se está haciendo mal y sólo está generando trabajo inútil por parte de todas partes implicadas (estudiante, revisores, y la IA que es la que de verdad esté generando el código).

2025-01-25 09:10 UTC, JJ commented on internal/models/sector.go
> +	valorPorOmisionParaElTipoFloat  = 0
Y como no estáis creando los issues tratando de entender porqué los hacéis y viendo su utilidad, sino para pasar de una pu*etera vez el objetivo, estás creando esto con un issue, el #55, que no sólo habla de un principio genérico (respetar responsabilidad única) en vez de un problema (que no tengo claro cuál será), sino que además en el mensaje de commit pone "se crean funciones nuevas", algo que no tiene absolutamente nada que ver con esta constante.

2025-01-26 11:12 UTC, FabriConde commented
@JJ Listo para revisar

2025-01-26 11:22 UTC, JJ commented
Acabo de decir por Telegram que no puedo revisar los próximos días y las alternativas. Te agradecería que leyeras lo que se dice en ese grupo, y obraras en consecuencia

2025-01-31 06:32 UTC, JJ commented
Podías haber enviado enlace al PR al grupo en estos cinco días, como dije.

2025-01-31 06:40 UTC, JJ reviewed
Me temo que mientras que no se entienda correctamente qué es un issue y para qué sirve, es imposible revisar esto, porque no se está desarrollando para satisfacer al cliente, sino simplemente como lo que se entiende que es el objetivo, y ya se ha dicho repetidamente que no lo es.
Como estamos a estas alturas, trataré de ver si se ha cubierto de alguna forma la parte fundamental, que es la línea de negocio. Pero de veras que deberías haber intentado ver exactamente qué es lo que se busca que aprendáis y pongáis en práctica aquí en vez de lanzarte a crear una docena de "issues" para cubrir el expediente.

2025-01-31 06:40 UTC, JJ commented on internal/models/sector.go
> +	posicionNombreVia               = 0
De veras que no entiendo muy bien por qué hacéis esto. Te has inventado un formato para escribir en texto las vías. No he visto por ningún sitio que ese formato se cree como respuesta a un issue. Y si no se hace así, es imposible de evaluar si es la forma más adecuada de representar un sector, si es completa, si estás poniendo al principio de una línea todo lo obligatorio y al final lo optativo, en suma, si estás haciendo lo mínimo que se exige para resolver los problemas que se implican con una historia de usuario.

2025-01-31 07:11 UTC, JJ requested changes
Lo siento que a estas alturas sea así, pero sin un enfoque sistemático de formulación de problemas y resolución de los mismos esto es simplemente un ejercicio académico de pedirle cosas a la IA y poner en el commit lo que se me ocurra, creando issues si acaso. No se trata de eso. Si desde el principio hubieras tratado de plantear problemas en los issues y resolverlos, habrías acabado ya, simplemente porque en ingeniería hay que trabajar siguiendo una metodología que garantice que se está añadiendo valor al cliente y se está trabajando con eficiencia en el tiempo de la empresa.
Cuando  te revisó @hossam1522 en noviembre, ["actualizaste" los issues](https://github.com/FabriConde/CLIMB-VR/pull/18#issuecomment-2503815634) en vez de plantear issues que fueran verdaderos problemas a resolver. 
En [este comentario](https://github.com/FabriConde/CLIMB-VR/pull/18#pullrequestreview-2492945353), el 10 de diciembre, te dije que tenía que añadir valor al cliente cualquier código que hicieras. A pesar de eso, seguiste sin crear los issues, seguiste añadiendo código apuntando a issues que no tenían nada que ver con los mismos [como te dije en este comentario](https://github.com/FabriConde/CLIMB-VR/pull/18#discussion_r1878455221) 
En [este comentario](https://github.com/FabriConde/CLIMB-VR/pull/18#pullrequestreview-2503028486) te dije que los issues eran problemas, no tearea. Eso fue el 13 de diciembre. Hace dos semanas creas issues como [demasiadas cadenas mágicas](https://github.com/FabriConde/CLIMB-VR/issues/48) que no señalan el problema *en el código* sino simplemente una tarea: eliminar cadenas mágicas. Si haces esto sin mirar como añadir valor al cliente, es decir, resolviendo el problema del cliente, *no estás haciendo nada*
El 30 de diciembre, el día antes de Nochevieja, [te dije que debías desarrollar siguiendo la metodología correcta](https://github.com/FabriConde/CLIMB-VR/pull/18#pullrequestreview-2525458552), la que te llevaba diciendo desde la primera revisión del código propiamente dicho. Hace ya un mes de eso.
He pasado posiblemente varias horas en la revisión de este objetivo. Sólo  hoy ya llevo casi tres cuartos de hora. En esas revisiones, te propongo soluciones específicas a problemas específicos en la realización del objetivo: tienes que seguir una metodología determinada, *la que viene en el guión*. Seguir esa metodología es la única que garantiza que se añada valor al cliente, simplemente porque es la única que garantiza que se estén resolviendo los problemas correctamente y que la persona que revisa (cualquier otro, yo) pueda entender las razones por las que se está añadiendo código. **No se trata de añadir mucho código**. No es un ejercicio, no es un examen. Es un proceso en el que se evalúa que se entienda la metodología y se siga. Por favor, hazlo así porque no te quedan muchas más oportunidades.

2025-01-31 15:47 UTC, FabriConde commented
@JJ Listo para revisar.
Por favor olvida los commit anteriores, porque son un lío, ya que he ido empalmando commits e issues y no se entiende nada.
Los nuevos issues son:
- #57 
- #58
- #59 
- #60 
- #61 
- #62 
- #63 
- #64 
- #65

2025-01-31 16:13 UTC, FabriConde commented
@JJ Listo para revisar.
Por favor olvida los commit anteriores, porque son un lío, ya que he ido empalmando commits e issues y no se entiende nada.
Los nuevos issues son:
- #57 
- #58
- #59 
- #60 
- #61 
- #62 
- #63 
- #64 
- #65

2025-01-31 16:21 UTC, JJ commented
No sé qué commits tendría que olvidar. Si están en el "blame" de una línea, siguen ahí. Si quieres eliminar los commits, haz squash de los commits para que se vea solo el último resultado y haz close de los issues que no vayas a solucionar en el cuerpo del PR .

2025-01-31 19:48 UTC, closed without merging